name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'src/site/notes/*.md'
      - 'src/site/notes/**/*.md'

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: mkdir output
      - name: Set up Docker
        run: docker pull fboaventura/dckr-pandoc
      - name: Generate PDF
        run: |
          docker run --rm \
            -v $(pwd)/src/site:/data \
            fboaventura/dckr-pandoc sh -c '
              find /data/notes -name "*.md" -print0 | xargs -0 pandoc --extract-media=. --to=plain --standalone --from=markdown+yaml_metadata_block+raw_html+tex_math_single_backslash -o $(pwd)/output/output.txt
              pandoc --pdf-engine=xelatex --variable mainfont=DejaVuSans $(pwd)/output/output.txt -o $(pwd)/output/output.pdf'
      - name: Upload PDF and TXT
        uses: actions/upload-artifact@master
        with:
          name: output
          path: /src/site/output
  get_pages_url:
    needs: convert_via_pandoc
    runs-on: ubuntu-latest
    steps:
      - name: Set Pages URL
        id: set_pages_url
        run: echo "PAGES_URL=https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}output/output.pdf" >> $GITHUB_ENV
      - name: Display Pages URL
        run: echo "${{ steps.set_pages_url.outputs.PAGES_URL }}"