name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'src/site/notes/*.md'
      - 'src/site/notes/**/*.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker pull fboaventura/dckr-pandoc

      - name: Generate PDF
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/data \
            -w /source \
            fboaventura/dckr-pandoc sh -c \
            'pandoc --pdf-engine=xelatex --variable mainfont=DejaVuSans src/site/notes/*.md -o output/output.pdf'

      - name: Upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: notes
          path: output