name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'src/site/notes/*.md'
      - 'src/site/notes/**/*.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        run: docker pull fboaventura/dckr-pandoc
      - name: Generate PDF
        run:
        docker run --name pandoc --rm \
   fboaventura/dckr-pandoc sh -c \
  'pandoc --pdf-engine=xelatex --variable mainfont=DejaVuSans *.md -o output.pdf'
      - uses: actions/upload-artifact@v3
        with:
          name: notes
          path: output
