name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'src/site/notes/*.md'
      - 'src/site/notes/**/*.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker pull fboaventura/dckr-pandoc

      - name: Generate PDF
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/src/site/notes:/data \
            -w /data \
            fboaventura/dckr-pandoc -c 'find . -name "*.md" -print0 | xargs -0 pandoc --extract-media=. --to=plain --standalone --from=markdown+yaml_metadata_block+raw_html+tex_math_single_backslash -o /data/pdfs/output.txt && pandoc --pdf-engine=xelatex --variable mainfont=DejaVuSans /data/pdfs/output.txt -o /data/pdfs/output.pdf'

      - name: Upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: notes
          path: pdfs